[mypy]
python_version = 3.11
mypy_path = src
explicit_package_bases = True
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
check_untyped_defs = True
no_implicit_optional = True
